# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f2a9bc9b398ce6f523adb801e1074e96fe0e2c11aeb27247c14d251c233a7a996889323ac6c8a81fcbcf8e2ac27d6a59600ecb508a3236ede5190456b66bc2

test:
  secret_key_base: 58849d13c173e6d318a5c9588c810a9a21bde20803af59d2163121631c2b5b9dbe912d5dcc0d6bde87674d2824e1b8089ebb8fc96a5ad378c0f28a633a675293

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
